# Generated by Django 5.2.8 on 2025-12-15 02:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_dailyincome_sand_of_amount_dailyincome_sand_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyincome',
            name='sand_of_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='dailyincome',
            name='sand_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
