# Generated by Django 5.2.8 on 2025-12-15 02:37

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_alter_dailyincome_sand_of_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyincome',
            name='sand_of_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='dailyincome',
            name='sand_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
