# Generated by Django 5.2.8 on 2025-12-15 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_alter_dailyincome_sand_of_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyincome',
            name='sand_of_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='dailyincome',
            name='sand_rate',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
