# Generated by Django 5.2.8 on 2025-12-15 03:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_alter_expense_amount_alter_partner_share_percentage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyincome',
            name='sand_of_amount',
        ),
        migrations.RemoveField(
            model_name='dailyincome',
            name='sand_rate',
        ),
        migrations.AlterField(
            model_name='dailyincome',
            name='amount',
            field=models.DecimalField(decimal_places=2, default='', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='expense',
            name='amount',
            field=models.DecimalField(decimal_places=2, default='', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='partner',
            name='share_percentage',
            field=models.DecimalField(decimal_places=2, default='', max_digits=5, validators=[django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='partnerpayout',
            name='share_amount',
            field=models.DecimalField(decimal_places=2, default='', max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='daily_rate',
            field=models.DecimalField(decimal_places=2, default='', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ship',
            name='purchase_cost',
            field=models.DecimalField(decimal_places=2, default=30000000.0, max_digits=10),
        ),
    ]
